version: '3.8'

services:
  ghostcrate:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:/data/ghostcrate.db
      - RUST_LOG=info
      - LEPTOS_SITE_ADDR=0.0.0.0:8080
    volumes:
      - ghostcrate_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ghostcrate_data:
    driver: local